[package]
name = "serbserver"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = "4.9.0"
serde_json = "1.0.133"
reqwest = {version = "0.12.9", features = ["json"]}
log = "0.4"
chrono = "0.4"
fern = "0.7"